/**
 * Session title generation using Google Gemini Flash API.
 * Generates concise, contextual titles from the first user message.
 */

import type { Env } from "../env.js";

const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent";

/**
 * Generate a session title based on the first user message.
 * Returns a 3-5 word title that captures the essence of the query.
 */
export async function generateSessionTitle(
  messageText: string,
  env: Env,
): Promise<string | null> {
  if (!env.GEMINI_API_KEY) {
    console.log("[TitleGen] No GEMINI_API_KEY configured, skipping auto-title");
    return null;
  }

  // Truncate very long messages for the prompt
  const truncatedText = messageText.slice(0, 500);

  const prompt = `Generate a concise, descriptive title (3-5 words max) for a chat session that starts with this message. The title should capture the main topic or intent. Respond with ONLY the title, no quotes, no punctuation, no explanation.

Message: "${truncatedText}"

Title:`;

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${env.GEMINI_API_KEY}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          temperature: 0.3,
          maxOutputTokens: 20,
          topP: 0.8,
        },
      }),
    });

    if (!response.ok) {
      console.error(`[TitleGen] Gemini API error: ${response.status} ${response.statusText}`);
      return null;
    }

    const data = await response.json() as {
      candidates?: Array<{
        content?: {
          parts?: Array<{ text?: string }>;
        };
      }>;
    };

    const title = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!title) {
      console.log("[TitleGen] No title generated");
      return null;
    }

    // Clean up the title - remove quotes, trim, limit length
    const cleanTitle = title
      .replace(/^["']|["']$/g, "") // Remove surrounding quotes
      .replace(/\n/g, " ") // Replace newlines with spaces
      .trim()
      .slice(0, 50); // Hard limit at 50 chars

    if (cleanTitle.length < 2) {
      console.log("[TitleGen] Generated title too short");
      return null;
    }

    console.log(`[TitleGen] Generated title: "${cleanTitle}" for message: "${truncatedText.slice(0, 50)}..."`);
    return cleanTitle;
  } catch (err) {
    console.error("[TitleGen] Error generating title:", err);
    return null;
  }
}

/**
 * Check if a session name was auto-generated (matches "Session N" pattern).
 * Returns true if the name matches the auto-generated pattern.
 */
export function isAutoGeneratedName(name: string): boolean {
  return /^Session \d+$/.test(name.trim());
}
